/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import com.dao.controlCategoria;
import com.modelo.categoria;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Banos
 */
public class categorias extends javax.swing.JFrame {
    
    String[] columnas = {"CODIGO", "NOMBRE", "DESCRIPCION"};
    DefaultTableModel model = new DefaultTableModel(columnas,0){
        @Override 
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    controlCategoria controlCat = new controlCategoria();
    List<categoria> datos = new ArrayList<>();
    categoria cat = new categoria();
    
    private void listarTbCat() {
        tbListarCat.getTableHeader().setReorderingAllowed(false);
        this.model.setRowCount(0);
        datos.clear();
        datos = (List<categoria>) controlCat.mostrarCategorias();
        Object[] obj = new Object[7];
        for (categoria fila : datos) {
            obj[0] = fila.getId_categoria();
            obj[1] = fila.getCategoria();
            obj[2] = fila.getDescripcionCat();
            this.model.addRow(obj);
        }
        this.tbListarCat.setModel(model);
    }
    
    public void limpiarCat(){
        this.txtNombreCat.setText("");
        this.txtDescripcionCat.setText("");          
    }

    /**
     * Creates new form categorias
     */
    public categorias() {
        initComponents();
        listarTbCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListarCat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblDescripcionCat = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtDescripcionCat = new javax.swing.JTextField();
        btnEditarCat = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblNombreCat = new javax.swing.JLabel();
        lblInsertarCat = new javax.swing.JLabel();
        btnGuardarCat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombreCat = new javax.swing.JTextField();
        btnBorrarCat = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        btnLimpiarCat = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarCat = new javax.swing.JTable();
        lblCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblListarCat.setText("Lista de categorias");

        jLabel6.setText("Buscar por:");

        jButton4.setText("Buscar");

        lblDescripcionCat.setText("Descripción");

        jButton5.setText("Limpiar");

        btnEditarCat.setText("Editar");
        btnEditarCat.setToolTipText("");
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });

        jButton7.setText("Regresar");

        lblNombreCat.setText("Categoria");

        lblInsertarCat.setText("Insertar categoria");

        btnGuardarCat.setText("Guardar");
        btnGuardarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCatActionPerformed(evt);
            }
        });

        btnBorrarCat.setText("Eliminar");
        btnBorrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCatActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Item 2", "Item 3", "Item 4" }));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLimpiarCat.setText("Limpiar");
        btnLimpiarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCatActionPerformed(evt);
            }
        });

        tbListarCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Categoria", "Descripción"
            }
        ));
        tbListarCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListarCatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListarCat);

        lblCodigo.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInsertarCat)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDescripcionCat)
                                .addComponent(txtDescripcionCat)
                                .addComponent(lblNombreCat)
                                .addComponent(txtNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuardarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(btnEditarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListarCat)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblListarCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInsertarCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblDescripcionCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcionCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnGuardarCat)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarCat)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrarCat)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarCat)
                                .addGap(38, 38, 38)
                                .addComponent(lblCodigo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCatActionPerformed
        // TODO add your handling code here:
        limpiarCat();
    }//GEN-LAST:event_btnLimpiarCatActionPerformed

    private void btnGuardarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCatActionPerformed
        // TODO add your handling code here:
        if(txtNombreCat.getText().equals("")||txtDescripcionCat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos solicitados !!");
        }else{
            this.cat.setCategoria(this.txtNombreCat.getText()); 
            this.cat.setDescripcionCat(this.txtDescripcionCat.getText());
            //this.lblNombreCat.setText(this.cat.getCategoria());
            //this.lblDescripcionCat.setText(this.cat.getDescripcionCat());
            if (this.controlCat.ingresarCategorias(this.cat)){
                JOptionPane.showMessageDialog(this,"Categoria guardada con exito !!");
                listarTbCat();
                limpiarCat();
            }else{
                JOptionPane.showMessageDialog(this,"Error al insertar");
            }
        }
    }//GEN-LAST:event_btnGuardarCatActionPerformed

    private void tbListarCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListarCatMouseClicked
        // TODO add your handling code here:
        this.txtNombreCat.setText(tbListarCat.getValueAt(tbListarCat.getSelectedRow(),1).toString());
        this.txtDescripcionCat.setText(tbListarCat.getValueAt(tbListarCat.getSelectedRow(),2).toString());
        this.lblCodigo.setText(tbListarCat.getValueAt(tbListarCat.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tbListarCatMouseClicked

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        // TODO add your handling code here:
        if(txtNombreCat.getText().equals("")||txtDescripcionCat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Existen datos vacio, verifique !!");
        }else{
            this.cat.setId_categoria(Integer.parseInt(this.lblCodigo.getText()));
            this.cat.setCategoria(this.txtNombreCat.getText());
            this.cat.setDescripcionCat(this.txtDescripcionCat.getText());
            if (this.controlCat.editarCategoria(this.cat)){
                JOptionPane.showMessageDialog(this,"Se ha modificado con exito!!");
                listarTbCat();
                limpiarCat();
            }else{
                JOptionPane.showMessageDialog(this,"Ha ocurrido un error al modificar");
            }
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void btnBorrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCatActionPerformed
        // TODO add your handling code here:
        if(txtNombreCat.getText().equals("")||txtDescripcionCat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Existen datos vacio, verifique !!");
        }else{ 
            this.cat.setId_categoria(Integer.parseInt(this.lblCodigo.getText()));
            this.cat.setCategoria(this.txtNombreCat.getText());
            this.cat.setDescripcionCat(this.txtDescripcionCat.getText());
            
            int resp = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la categoria ??", "Advertencia !!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (resp==JOptionPane.YES_OPTION)
            {
                if (this.controlCat.EliminarCategoria(this.cat)){
                    JOptionPane.showMessageDialog(this,"Categoria eliminada !!");
                    listarTbCat();
                    limpiarCat();
                }else{
                    JOptionPane.showMessageDialog(this,"La categoria no se ha eliminado !!");
                }
            }
        }
    }//GEN-LAST:event_btnBorrarCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categorias().setVisible(true);
            }
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarCat;
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnGuardarCat;
    private javax.swing.JButton btnLimpiarCat;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcionCat;
    private javax.swing.JLabel lblInsertarCat;
    private javax.swing.JLabel lblListarCat;
    private javax.swing.JLabel lblNombreCat;
    private javax.swing.JTable tbListarCat;
    private javax.swing.JTextField txtDescripcionCat;
    private javax.swing.JTextField txtNombreCat;
    // End of variables declaration//GEN-END:variables

}
