/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import db_conexion.cConexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Banos
 */
public class InicioSesion extends javax.swing.JFrame {
    Connection conn;
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/banana.png")).getImage());
        cConexion con = new cConexion();
        conn = con.conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIniciarSesion = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblDui = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        cbxPass = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion");
        setResizable(false);

        pnIniciarSesion.setBackground(new java.awt.Color(205, 242, 205));
        pnIniciarSesion.setForeground(new java.awt.Color(255, 204, 255));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario6.png"))); // NOI18N
        lblNombre.setText("INICIO DE SESION");

        txtDui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuiKeyTyped(evt);
            }
        });

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        lblDui.setText("Numero de DUI");

        lblPass.setText("Contraseña");

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contra.png"))); // NOI18N
        btnRegistrar.setText("¿Olvido su contraseña?");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(255, 204, 102));
        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login9.png"))); // NOI18N
        btnIniciar.setText("Ingresar al sistema");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        cbxPass.setText("Mostrar contraseña");
        cbxPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPassActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(204, 204, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventaio.png"))); // NOI18N
        btnVolver.setText("Volver al inicio");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnIniciarSesionLayout = new javax.swing.GroupLayout(pnIniciarSesion);
        pnIniciarSesion.setLayout(pnIniciarSesionLayout);
        pnIniciarSesionLayout.setHorizontalGroup(
            pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIniciarSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIniciarSesionLayout.createSequentialGroup()
                        .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIniciarSesionLayout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(pnIniciarSesionLayout.createSequentialGroup()
                .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnIniciarSesionLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIniciarSesionLayout.createSequentialGroup()
                                .addComponent(lblDui)
                                .addGap(18, 18, 18)
                                .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnIniciarSesionLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblPass)
                                .addGap(18, 18, 18)
                                .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxPass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnIniciarSesionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnIniciarSesionLayout.setVerticalGroup(
            pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIniciarSesionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblNombre)
                .addGap(47, 47, 47)
                .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDui)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxPass)
                .addGap(52, 52, 52)
                .addComponent(btnIniciar)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuiKeyTyped
        // TODO add your handling code here:
        char vDui = evt.getKeyChar();
        boolean asciiBS = vDui == 8;
        int cDui = txtDui.getText().length(); 
        
        if(!Character.isDigit(vDui) && !asciiBS){
            //getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo permite ingresar numeros, segun el formato del numero de DUI", "Formato de DUI invalido", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(cDui >= 9){
            evt.consume();
        }
    }//GEN-LAST:event_txtDuiKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        // TODO add your handling code here:
        int cPass = String.valueOf(txtPass.getPassword()).length();
        
        if(cPass >= 12){
            evt.consume();
        }
    }//GEN-LAST:event_txtPassKeyTyped

    private void cbxPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPassActionPerformed
        // TODO add your handling code here:
        if(cbxPass.isSelected()){
            txtPass.setEchoChar((char)0);
        }else{
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_cbxPassActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        int type_user, usId;
        String usNombre, usApellido, usCargo;
        String usDui = txtDui.getText();
        int cDui = txtDui.getText().length();
        String usPass = String.valueOf(txtPass.getPassword());
        int cPass = usPass.length();
        

        if(usDui.equals("") || usPass.equals("")){
            JOptionPane.showMessageDialog(null, "Verfique la informacion ingresada, ya que uno o ambos datos solicitados estan vacios", "Datos vacios", JOptionPane.ERROR_MESSAGE);
        }else if(cDui <= 8){
            JOptionPane.showMessageDialog(null, "El numero de DUI debe tener 9 caracteres", "Dui incompleto", JOptionPane.WARNING_MESSAGE);
        }else if(cPass <= 7){
            JOptionPane.showMessageDialog(null, "La contraseña debe tener 8 o mas caracteres", "Contraseña incompleta", JOptionPane.WARNING_MESSAGE);
        }else{
            String sql = "SELECT id_tipoUsuario, usNombre, usApellido, usCargo, id_usuario FROM Usuario WHERE usDui='"+usDui+"' AND usPasswd='"+usPass+"'";

            try {
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if(rs.next()){
                    type_user = rs.getInt("id_tipoUsuario");
                    usNombre = rs.getString("usNombre");
                    usApellido = rs.getString("usApellido");
                    usCargo = rs.getNString("usCargo");
                    usId = rs.getInt("id_usuario");
                    if(type_user == 1){
                        JOptionPane.showMessageDialog(null, "Bienvenida/o "+usCargo+", El acceso de "+usNombre+" "+usApellido+" ha sido verificado con exito", "Inicio de sesion", JOptionPane.INFORMATION_MESSAGE);
                        MenuAdmin newForm = new MenuAdmin();
                        newForm.obtenerDatos(type_user, usNombre, usApellido, usDui, usCargo, usId);
                        newForm.setVisible(true);
                        newForm.setLocationRelativeTo(null);
                        this.dispose();
                        conn.close();
                    }else if(type_user == 2){
                        JOptionPane.showMessageDialog(null, "Bienvenida/o "+usCargo+", El acceso de "+usNombre+" "+usApellido+" se ha verificado", "Inicio de sesion", JOptionPane.INFORMATION_MESSAGE);
                        Menu newForm = new Menu();
                        newForm.obtenerDatos(type_user, usNombre, usApellido, usDui, usCargo, usId);
                        newForm.setVisible(true);
                        newForm.setLocationRelativeTo(null);
                        this.dispose();
                        conn.close();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Los datos ingresados son incorrectos, Por favor verfique uno o ambos", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
                }
                //ps.close();
                //res.close();
                //conn.close();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error: "+e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        PreguntaUsuario newForm = new PreguntaUsuario();
        newForm.setLocationRelativeTo(null);
        newForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        InicioArticulos newForm = new InicioArticulos();
        newForm.setLocationRelativeTo(null);
        newForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox cbxPass;
    private javax.swing.JLabel lblDui;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPass;
    private javax.swing.JPanel pnIniciarSesion;
    private javax.swing.JTextField txtDui;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
