/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import com.dao.controlArticulo;
import com.modelo.articulo;
import db_conexion.cConexion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Banos
 */
public class InicioArticulos extends javax.swing.JFrame {
    cConexion con = new cConexion();
    String[] columnas = {"ID", "CODIGO", "NOMBRE", "CANTIDAD", "ESTADO", "COMENTARIO", "USID", "CATID", "USUARIO", "CATEGORIA"};
    DefaultTableModel model = new DefaultTableModel(columnas,0){
        @Override 
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    controlArticulo controlArt = new controlArticulo();
    List<articulo> datos = new ArrayList<>();
    articulo art = new articulo();
    
    private void CargarDatos() {
        tbListarArt.getTableHeader().setReorderingAllowed(false);
        this.model.setRowCount(0);
        datos.clear();
        datos = (List<articulo>) controlArt.mostrarArticulos();
        Object[] obj = new Object[10];
        for (articulo fila : datos) {
            obj[0] = fila.getId_articulo();
            obj[1] = fila.getArtCodigo();
            obj[2] = fila.getArtNombre();
            obj[3] = fila.getArtCantidad();
            obj[4] = fila.getArtEstado();
            obj[5] = fila.getArtComentario();
            obj[6] = fila.getId_usuario();
            obj[7] = fila.getId_categoria();
            obj[8] = fila.getUsDui();
            obj[9] = fila.getCatNombre();
            this.model.addRow(obj);
        }
        this.tbListarArt.setModel(model);
    }
    
    private void BuscarDatos(){
        tbListarArt.getTableHeader().setReorderingAllowed(false);
        model.setRowCount(0);
        datos.clear();
        String frase = txtBuscar.getText();
        datos = (List<articulo>) controlArt.buscarArticulo(frase);
        Object[] obj = new Object[10];
        for (articulo fila : datos) {
            obj[0] = fila.getId_articulo();
            obj[1] = fila.getArtCodigo();
            obj[2] = fila.getArtNombre();
            obj[3] = fila.getArtCantidad();
            obj[4] = fila.getArtEstado();
            obj[5] = fila.getArtComentario();
            obj[6] = fila.getId_usuario();
            obj[7] = fila.getId_categoria();
            obj[8] = fila.getUsDui();
            obj[9] = fila.getCatNombre();
            model.addRow(obj);
        }
        tbListarArt.setModel(model);
    }
    
    private void hideTb(){
        tbListarArt.getColumnModel().getColumn(0).setMinWidth(1);
        tbListarArt.getColumnModel().getColumn(0).setMaxWidth(1);
        tbListarArt.getColumnModel().getColumn(0).setWidth(1);
        tbListarArt.getColumnModel().getColumn(6).setMinWidth(1);
        tbListarArt.getColumnModel().getColumn(6).setMaxWidth(1);
        tbListarArt.getColumnModel().getColumn(6).setWidth(1);
        tbListarArt.getColumnModel().getColumn(7).setMinWidth(1);
        tbListarArt.getColumnModel().getColumn(7).setMaxWidth(1);
        tbListarArt.getColumnModel().getColumn(8).setWidth(1);
        tbListarArt.getColumnModel().getColumn(8).setMinWidth(1);
        tbListarArt.getColumnModel().getColumn(8).setMaxWidth(1);
        tbListarArt.getColumnModel().getColumn(8).setWidth(1);
    }

    /**
     * Creates new form InicioArticulos
     */
    public InicioArticulos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/banana.png")).getImage());
        this.setLocationRelativeTo(null);
        CargarDatos();
        hideTb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarArt = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnInicioSE = new javax.swing.JButton();
        btnRecargarTb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        tbListarArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Categoria", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tbListarArt);

        lblBuscar.setText("Buscar por:");

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informacion.png"))); // NOI18N
        lblInfo.setText("INFORMACION DE LOS ARTICULOS REGISTRADOS ");

        btnInicioSE.setBackground(new java.awt.Color(204, 204, 255));
        btnInicioSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil2.png"))); // NOI18N
        btnInicioSE.setText("Iniciar sesion");
        btnInicioSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSEActionPerformed(evt);
            }
        });

        btnRecargarTb.setBackground(new java.awt.Color(204, 204, 255));
        btnRecargarTb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cambiar.png"))); // NOI18N
        btnRecargarTb.setText("Recargar tabla");
        btnRecargarTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarTbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lblInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRecargarTb))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInicioSE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                        .addComponent(lblBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(btnInicioSE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRecargarTb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarTbActionPerformed
        // TODO add your handling code here:
        CargarDatos();
    }//GEN-LAST:event_btnRecargarTbActionPerformed

    private void btnInicioSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSEActionPerformed
        // TODO add your handling code here:
        InicioSesion newForm = new InicioSesion();
        newForm.setVisible(true);
        newForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnInicioSEActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        BuscarDatos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInicioSE;
    private javax.swing.JButton btnRecargarTb;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tbListarArt;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
