/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import db_conexion.cConexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Banos
 */
public class PreguntaUsuario extends javax.swing.JFrame {
    
    private void obtenerpregunta(){
        cConexion con = new cConexion();
        //usNombre, usApellido, usPregunta,
        String usDui = txtDui.getText();
        String usPregunta, usRespuesta, usId;
        String sql = "SELECT id_usuario, usPregunta, usRespuesta FROM usuario WHERE usDui = '"+usDui+"'";
        PreparedStatement ps;
        ResultSet res;
        try {
            ps = con.conexion().prepareStatement(sql);
            res = ps.executeQuery();
            if(res.next()){
                usPregunta = res.getString("usPregunta");
                txtPregunta.setText(usPregunta);
                usRespuesta = res.getString("usRespuesta");
                lblRespuestaDB.setText(usRespuesta);
                usId = Integer.toString(res.getInt("id_usuario"));
                lblId.setText(usId);
            }else{
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: "+e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }
    
    private void bloquearDatos(){
        txtPregunta.setEnabled(false);
        txtRespuesta.setEnabled(false);
        btnRespuesta.setEnabled(false);
        lblRespuestaDB.setVisible(false);
        lblId.setVisible(false);
    }
    
    private void ResponderPregunta(){
       btnDui.setEnabled(false);
       txtDui.setEnabled(false);
       txtPregunta.setEnabled(true);
       txtPregunta.setEditable(false);
       txtRespuesta.setEnabled(true);
       btnRespuesta.setEnabled(true);
    }
    
    private void NuevoDui(){
       txtDui.setEnabled(true);
       txtDui.setText("");
       btnDui.setEnabled(true);
       txtPregunta.setEnabled(false);
       txtRespuesta.setEnabled(false);
       txtPregunta.setText("");
       txtRespuesta.setText("");
       btnRespuesta.setEnabled(false);
    }
    

    /**
     * Creates new form PreguntaUsuario
     */
    public PreguntaUsuario() {
        initComponents();
        bloquearDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDui = new javax.swing.JLabel();
        btnDui = new javax.swing.JButton();
        txtDui = new javax.swing.JTextField();
        lblRespuestaDB = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPregunta = new javax.swing.JLabel();
        txtPregunta = new javax.swing.JTextField();
        txtRespuesta = new javax.swing.JTextField();
        lblRespuesta = new javax.swing.JLabel();
        btnRespuesta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDui.setText("Ingresar el numero de DUI");

        btnDui.setText("Comprobar DUI");
        btnDui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuiActionPerformed(evt);
            }
        });

        txtDui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuiKeyTyped(evt);
            }
        });

        lblRespuestaDB.setText("RespuestaDB");

        lblId.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDui)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRespuestaDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDui, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblId)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDui)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDui)
                    .addComponent(lblRespuestaDB)
                    .addComponent(lblId))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblPregunta.setText("Pregunta");

        txtRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuestaKeyTyped(evt);
            }
        });

        lblRespuesta.setText("Repuesta");

        btnRespuesta.setText("Comprobar respuesta");
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });

        jLabel1.setText("Responda la pregunta adecuadamente para poder cambiar su contraseña.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRespuesta)
                                .addComponent(lblPregunta))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPregunta)
                                .addComponent(txtRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(btnRespuesta)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPregunta)
                    .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespuesta)
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRespuesta)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuiKeyTyped
        // TODO add your handling code here:
        char vDui = evt.getKeyChar();
        boolean asciiBS = vDui == 8;
        int cDui = txtDui.getText().length(); 
        
        if(!Character.isDigit(vDui) && !asciiBS){
            //getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo permite ingresar numeros, segun el formato del numero de DUI", "Formato de dato invalido", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(cDui >= 9){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtDuiKeyTyped

    private void txtRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuestaKeyTyped
        // TODO add your handling code here:
        int cRespuesta = String.valueOf(txtRespuesta.getText()).length();
        
        if(cRespuesta >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_txtRespuestaKeyTyped

    private void btnDuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuiActionPerformed
        // TODO add your handling code here:
        String usDui = txtDui.getText();
        if(usDui.equals("")){
            JOptionPane.showMessageDialog(null, "Actualmente el DUI esta vacio, Ingrese su DUI para poder obtener continuar con el proceso de cambiar su contraseña ", "DUI vacio", JOptionPane.INFORMATION_MESSAGE);       
        }else if(usDui.length() <= 8){
            JOptionPane.showMessageDialog(null, "El numero de DUI debe tener un total de 9 caracteres", "Dui incompleto", JOptionPane.INFORMATION_MESSAGE);
        }else{
            ResponderPregunta();
            obtenerpregunta();
        } 
    }//GEN-LAST:event_btnDuiActionPerformed

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        // TODO add your handling code here:
        String usResp = txtRespuesta.getText();
        String dbResp = lblRespuestaDB.getText();
        String usId = lblId.getText();
        if(usResp.equals("")){
            JOptionPane.showMessageDialog(null, "Verifique su respuesta, el campo actualemnte se encuentra vacio", "Respuesta vacio", JOptionPane.INFORMATION_MESSAGE);
        }else if (dbResp.equals(usResp)){
            int resp = JOptionPane.showConfirmDialog(null, "¿Confirme si desea cambiar su contraseña actual por una nueva contraseña?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (resp==JOptionPane.YES_OPTION){
                CambiarPass newForm = new CambiarPass();
                newForm.obtenerDato(usId);
                newForm.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Se ha cancelado el cambio de contraseña", "Cambio de contraseña cancelado", JOptionPane.INFORMATION_MESSAGE);
                NuevoDui();
            }
        }else{
            JOptionPane.showMessageDialog(null, "La actual respuesta no es igual, compruebe que la esta escribiendo de manera correcta", "Respuesta incorrecta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDui;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDui;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblRespuestaDB;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtPregunta;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
